== TLS Functional Package

[cols="1,1,1,1,1,1,1,1"]
|===
8+|tls 
| https://github.com/commoncriteria/tls/tree/release-1.1[release-1.1] 
a| https://commoncriteria.github.io/tls/release-1.1/tls-release.html[📄]
a|[link=https://github.com/commoncriteria/tls/blob/gh-pages/release-1.1/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/tls/gh-pages/release-1.1/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/tls/blob/gh-pages/release-1.1/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/tls/gh-pages/release-1.1/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/tls/blob/gh-pages/release-1.1/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/tls/gh-pages/release-1.1/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/tls/blob/gh-pages/release-1.1/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/tls/gh-pages/release-1.1/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/tls/gh-pages/release-1.1/transforms.svg[transforms,150]
a| [link=https://github.com/commoncriteria/tls/blob/gh-pages/release-1.1/HTMLs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/tls/gh-pages/release-1.1/html_count.svg[HTML Count]
[link=https://github.com/commoncriteria/tls/blob/gh-pages/release-1.1/PDFs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/tls/gh-pages/release-1.1/pdf_count.svg[PDF Count]
|===


https://github.com/commoncriteria/tls/issues[image:https://img.shields.io/github/issues/commoncriteria/tls.svg?maxAge=2592000[GitHub
issues Open]]
image:https://img.shields.io/badge/license-Unlicensed-blue.svg[license]

This repository hosts the draft version of the Package for TLS based on
the https://commoncriteria.github.io/pp/tls/tls-esr.html[Essential
Security Requirements (ESR)] for products which implement this
technology. This repository is used to facilitate collaboration and
development on the draft document. See the
link:#Release-Version[release] section if you are looking for the
officially released version for evaluations.

=== Draft Version

* https://commoncriteria.github.io/pp/tls/tls-release.html[Package for
TLS] (html)
* https://commoncriteria.github.io/pp/tls/tls.html[Package for TLS in
heretical reader-friendly format] (html)
* https://commoncriteria.github.io/pp/tls/tls-release.pdf[Package for
TLS] (pdf)

=== Release Version

* https://www.niap-ccevs.org/Profile/Info.cfm?PPID=426&id=426[Protection
Profile - Functional Package for TLS]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community. *
https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/tls/issues[repository issue tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive https://github.com/commoncriteria/tls.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
