== Functional Package for TLS

[cols="1,1,1,1,1,1,1,1"]
|===
8+|tls 
| https://github.com/commoncriteria/tls/tree/master[master] 
a| https://commoncriteria.github.io/tls/master/tls-release.html[📄]
a|[link=https://github.com/commoncriteria/tls/blob/gh-pages/master/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/tls/gh-pages/master/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/tls/blob/gh-pages/master/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/tls/gh-pages/master/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/tls/blob/gh-pages/master/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/tls/gh-pages/master/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/tls/blob/gh-pages/master/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/tls/gh-pages/master/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/tls/gh-pages/master/transforms.svg[transforms,150]
a| 
https://commoncriteria.github.io/tls/master/diff-release-1.1.html[diff-release-1.1.html] +
https://commoncriteria.github.io/tls/master/tls-release-linkable.html[tls-release-linkable.html] +
https://commoncriteria.github.io/tls/master/tls-release.html[tls-release.html] +
https://commoncriteria.github.io/tls/master/tls.html[tls.html] +
|===


This repository hosts the draft version of the Functional Package for
TLS based on the
https://commoncriteria.github.io/pp/tls/tls-esr.html[Essential Security
Requirements (ESR)] for products which implement this technology. This
repository is used to facilitate collaboration and development on the
draft document. See the link:#Release-Version[release] section if you
are looking for the officially released version for evaluations.

=== Draft Version

* https://commoncriteria.github.io/pp/tls/tls-release.html[Functional
Package for TLS] (html)
* https://commoncriteria.github.io/pp/tls/tls.html[Functional Package
for TLS in heretical reader-friendly format] (html)
* https://commoncriteria.github.io/pp/tls/tls-release.pdf[Functional
Package for TLS] (pdf)
* https://commoncriteria.github.io/tls/diff-v1.1.html[Visual Diff
against 1.1](html)

=== Release Version

* https://www.niap-ccevs.org/Profile/Info.cfm?PPID=426&id=426[Protection
Profile - Functional Package for TLS]

=== Contributing

If you are interested in contributing directly to future versions the
this Functional Package, please consider joining the NIAP technical
community. *
https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/tls/issues[repository issue tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive https://github.com/commoncriteria/tls.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
